name: stow_codecs
description: A collection of codecs which can be used with Stow.
version: 1.4.0
resolution: workspace
repository: https://github.com/adil192/stow

topics:
  - stow
  - codec

environment:
  sdk: ^3.8.0
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.16.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
